# This workflow will install Python dependencies, run tests and lint with all active versions of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on: [push, pull_request]

jobs:
  ci:

    runs-on: self-hosted

    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
    - name: Analysing the code with pylint
      env:
        PYTHONPATH: .
      run: |
        pylint `ls -R|grep .py$|xargs`
    - name: Test with pytest
      env:
        PYTHONPATH: .
      run: |
        pytest --cov=./